#!/bin/bash
drwxr-xr-x 4 root root   60 Sep  1 01:12 ../-rwxr--r-- 1 root root   16 Sep  1 01:14 0-current_working_directory/-rwxr--r-- 1 root root   85 Sep  1 02:37 1-listit/-rwxr--r-- 1 root root   15 Sep  1 02:44 2-bring_me_home/-rw------- 1 root root 4096 Sep  1 02:43 .2.swp/-rw-r--r-- 1 root root   13 Sep  1 02:47 3-listfiles/-rw-r--r-- 1 root root   16 Sep  1 01:36 README.md  
